import { defineConfig } from "vite";
import path from "path";

// https://vitejs.dev/config
export default defineConfig({
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  build: {
    sourcemap: true,
    rollupOptions: {
      external: [
        "better-sqlite3",
        "node-fetch",
        "isomorphic-git",
        "electron-log",
        "crypto-js",
        "uuid",
        "axios",
        "openai",
        "e2b",
        "drizzle-orm",
        "neon-serverless",
        "glob",
        "fs-extra",
        "kill-port",
        "tree-kill",
        "p-queue",
        "stacktrace-js",
        "update-electron-app",
        "electron-squirrel-startup",
        "fix-path",
        "shell-env",
        "dotenv",
        "cheerio",
        "posthog-js",
        "sonner",
        "react-markdown",
        "remark-gfm",
        "shiki",
        "react-shiki",
        "lexical",
        "lexical-beautiful-mentions",
        "monaco-editor",
        "framer-motion",
        "cmdk",
        "date-fns",
        "zod",
        "jotai",
        "clsx",
        "tailwind-merge",
        "class-variance-authority",
        "lucide-react",
        "geist",
        "tw-animate-css",
        "react-resizable-panels",
        "@radix-ui/react-accordion",
        "@radix-ui/react-alert-dialog",
        "@radix-ui/react-checkbox",
        "@radix-ui/react-dialog",
        "@radix-ui/react-dropdown-menu",
        "@radix-ui/react-label",
        "@radix-ui/react-popover",
        "@radix-ui/react-progress",
        "@radix-ui/react-scroll-area",
        "@radix-ui/react-select",
        "@radix-ui/react-separator",
        "@radix-ui/react-slot",
        "@radix-ui/react-switch",
        "@radix-ui/react-tabs",
        "@radix-ui/react-toggle",
        "@radix-ui/react-toggle-group",
        "@radix-ui/react-tooltip",
        "@tanstack/react-query",
        "@tanstack/react-router",
        "@ai-sdk/amazon-bedrock",
        "@ai-sdk/anthropic",
        "@ai-sdk/azure",
        "@ai-sdk/google",
        "@ai-sdk/google-vertex",
        "@ai-sdk/openai",
        "@ai-sdk/openai-compatible",
        "@ai-sdk/provider-utils",
        "@ai-sdk/xai",
        "@openrouter/ai-sdk-provider",
        "@modelcontextprotocol/sdk",
        "@neondatabase/api-client",
        "@neondatabase/serverless",
        "@vercel/sdk",
        "@dyad-sh/supabase-management-js",
        "@monaco-editor/react",
        "@lexical/react",
        "@tailwindcss/typography",
        "@tailwindcss/vite",
        "@vitejs/plugin-react",
        "@rollup/plugin-commonjs",
        "ai",
        "react",
        "react-dom",
        "tailwindcss"
      ],
    },
  },
  plugins: [
    {
      name: "restart",
      closeBundle() {
        process.stdin.emit("data", "rs");
      },
    },
  ],
});
