# .github/workflows/release-simple.yml

# Simplified release workflow that doesn't require code signing certificates
permissions:
  contents: write

name: Release app (Simple)
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [
            { name: "windows", image: "windows-latest" },
            { name: "linux", image: "ubuntu-22.04" },
            { name: "macos", image: "macos-15" },
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Github checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Use Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 20
      - run: npm ci
        
      # Build and package (without code signing)
      - name: Build and package
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: npm run make
        
      # Upload artifacts for manual release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: codex-${{ matrix.os.name }}-${{ github.run_number }}
          path: out/
          retention-days: 30

  # Optional: Create a draft release with all artifacts
  create-release:
    name: Create Draft Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          name: "CodeX v${{ github.run_number }} - Draft Release"
          body: |
            ## CodeX v${{ github.run_number }}
            
            This is a draft release with unsigned builds for testing purposes.
            
            ### Downloads:
            - Windows: Download the Windows artifact
            - macOS: Download the macOS artifact  
            - Linux: Download the Linux artifact
            
            **Note**: These builds are not code-signed and may show security warnings.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
